# .pre-commit-config.yaml # this is hook
repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.14.10  # <-- update to latest version
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/psf/black
    rev: 25.12.0
    hooks:
      - id: black

