# ============================================================================
# FILE: docker-compose.yml
# ============================================================================

services:
  postgres:
    image: postgres:15-alpine
    container_name: earthquake-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME_POST}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
#      POSTGRES_DB: earthquake_db
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/schema/01_raw_layer.sql:/docker-entrypoint-initdb.d/01_raw_layer.sql
      - ./sql/schema/02_staging_layer.sql:/docker-entrypoint-initdb.d/02_staging_layer.sql
      - ./sql/schema/03_warehouse_layer.sql:/docker-entrypoint-initdb.d/03_warehouse_layer.sql
      - ./sql/init_airflow_db.sql:/docker-entrypoint-initdb.d/99_init_airflow_db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-init:
    image: earthquake-airflow:latest
    container_name: airflow-init
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      # AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@earthquake-db:5432/airflow_db
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:${DB_PASSWORD}@${DB_HOST}:5432/airflow_db
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    command: ["airflow", "db", "init"]
    restart: "no"

  airflow-webserver:
    image: earthquake-airflow:latest
    container_name: airflow-webserver
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      #AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@earthquake-db:5432/airflow_db
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:${DB_PASSWORD}@${DB_HOST}:5432/airflow_db
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: "mysecretkey123"
      AIRFLOW__LOGGING__REMOTE_LOGGING: "False"
      AIRFLOW__LOGGING__LOGGING_LEVEL: "INFO"

      # App DB (earthquake_elt)
#      DB_HOST: earthquake-db
#      DB_PORT: "5432"
#      DB_NAME: earthquake_db
#      DB_USER: postgres
#      DB_PASSWORD: postgres
      # App DB used by earthquake_elt
      DB_HOST: ${DB_HOST}
      DB_PORT: "${DB_PORT}"
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./config:/opt/airflow/config
      - ./sql:/opt/airflow/sql
    ports:
      - "8080:8080"
    command: ["airflow", "webserver"]

  airflow-scheduler:
    image: earthquake-airflow:latest
    container_name: airflow-scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      #AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@earthquake-db:5432/airflow_db
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:${DB_PASSWORD}@${DB_HOST}:5432/airflow_db
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: "mysecretkey123"
      AIRFLOW__LOGGING__REMOTE_LOGGING: "False"
      AIRFLOW__LOGGING__LOGGING_LEVEL: "INFO"

      # App DB used by earthquake_elt
      DB_HOST: ${DB_HOST}
      DB_PORT: "${DB_PORT}"
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./config:/opt/airflow/config
      - ./sql:/opt/airflow/sql
    command: ["airflow", "scheduler"]

volumes:
  postgres_data:
